TRUNCATE TABLE subject_legend;
INSERT INTO subject_legend
VALUES ('ADA', 'Analisis y Diseño de Algoritmos'),
    ('AL', 'Algebra Lineal'),
    ('ALG', 'Algebra'),
    ('BDA', 'Base de Datos Avanzadas'),
    ('CD', 'Calculo Diferencial'),
    ('CI', 'Calculo Integral'),
    ('CS', 'Ciberseguridad'),
    ('CV', 'Calculo Vectorial'),
    ('DAM', 'Desarrollo de Aplicaciones Moviles'),
    ('DAW', 'Desarrollo de Aplicaciones Web'),
    ('DIP', 'Procesamiento de Imagenes'),
    ('ED', 'Ecuaciones Diferenciales'),
    ('FIS', 'Fisica'),
    ('GT', 'Teoria de Juegos'),
    ('IA', 'Inteligencia Artificial'),
    ('MEC', 'Mecanica'),
    ('PA', 'Programacion Avanzada'),
    ('PED', 'Programacion y Estructura de Datos'),
    ('POO', 'Programacion Orientada a Objetos'),
    ('SO', 'Sistemas Operativos'),
    ('TER', 'Termodinamica'),
    ('TG', 'Teoria de Graficas'),
    ('TLP', 'Teoria y Lenguajes de Programacion');
